Revert "Fix vulnerability in MemoryIntArray"
This reverts commit 9e44c855ab58281de43197ae0ffc548f32ffa90e [formerly 86dfa094de773670743d41c3e3156eace8e403a3].


BROKE BUILD (as shown in some treehugger builds)

frameworks/base/core/java/android/util/MemoryIntArray.java:84: error: cannot find symbol
        mCloseGuard.open("close");
        ^
        
       
bug:33039926
bug:33042690

Change-Id: Ief875e543ec849fe55c747fb1ed5253f0cd9a122

Former-commit-id: 29139a8ae51110b0cd9d6249f643364849d401c9