Fixed NetworkStatsServiceTest and converted it to JUnit4.
Most tests were failing because due to a null NetworkCapabilities.
Example:

1) testNetworkStatsWifi(com.android.server.net.NetworkStatsServiceTest)
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.net.NetworkCapabilities.hasCapability(int)' on a null object reference
	at
	com.android.server.net.NetworkStatsService.updateIfacesLocked(NetworkStatsService.java:983)

BUG: 30839080

(cherry picked from commit 0e91eae9c3d0e8831e403a39e2f7ebc78f6bbafb [formerly 574f370c6da52eeffe747248d68ef044617c7bcf])

Change-Id: Ie09b2f43cf6ec745e404d5ec98bd0b072d211ea3

Former-commit-id: 439ac32c7cd9c92a6efaac3ebdf0c584c69c4318