Fix warning from clang+mingw
I suspect this is showing up in this configuration because we're now building
with -std=gnu++14, but still using libstdc++.

frameworks/base/tools/aapt2/link/ProductFilter_test.cpp:76:24: error: chosen constructor is explicit in copy-initialization
  ProductFilter filter({});
                       ^~
prebuilts/gcc/linux-x86/host/x86_64-w64-mingw32-4.8/x86_64-w64-mingw32/include/c++/4.8.3/bits/unordered_set.h:132:7: note: explicit constructor declared here
      unordered_set(size_type __n = 10,
      ^
frameworks/base/tools/aapt2/link/Linkers.h:114:58: note: passing argument to parameter 'products' here
  explicit ProductFilter(std::unordered_set<std::string> products) : products_(products) {
                                                         ^

Bug: 69933068
Test: mmma frameworks/base/tools/aapt2
Test: out/host/linux-x86/nativetest[64]/aapt2_tests/aapt2_tests
Change-Id: I2133e364dd11f64fd13239125f8a3eff70ebb69c

Former-commit-id: fb4ed78bde052502861c913e1853f888ea297d2a