Add missing WARN_UNUSED attribute
The upcoming compiler update warns against missing WARN_UNUSED
attribute:

  frameworks/base/cmds/idmap2/libidmap2/Idmap.cpp:58:3: error: function 'Map' should be marked [[nodiscard]] [modernize-use-nodiscard,-warnings-as-errors]
    inline const std::map<TypeId, std::set<std::pair<ResourceId, ResourceId>>>& Map() const {
    ^
    [[nodiscard]]

Test: m checkbuild
Bug: 126457671
Change-Id: Ib006dacbc17446377b2886c73190548f53429a44

Former-commit-id: 974d516e5f9f7af65462bb3dded5becf3fc32c43