Workaround for javac compilation issue of lambda code
Since ag/32554459 some Robolectric tests are compiling
framework code with javac. For reasons unclear so far this
code fails to compile with javac:

> ShortcutService.java:408: error: variable ri might not have been initialized

https://android-build.googleplex.com/builds/submitted/3416256/angelfish-userdebug/latest/logs

Removing the lambda expressions corrects the issue.

(cherry picked from commit e8beb032fee5b4e92ecb0b9c9c3865a9787cfd13 [formerly e065f7c5a9ad4e47f5490793401445660af37624])

BUG: 32554459
Test: m
Change-Id: I189c8ef02dc93b46ef6418c1ff14f2312097898a

Former-commit-id: cc3fad30975e66875588d87e7e6c7af9a35b62fd