[ActivityManager] Fix index OOB when updating visible.
If there is an Activity Z of Task T needs be visible but
isn't running, and the process P of Z is existed, it will
just to schedule launch Z.

The problem will happen when P is died (e.g. kill itself)
right before scheduleLaunchActivity. Once RemoteException
is caught, startSpecificActivityLocked will try to restart
the process and run cleanup procedure because the process
record is existed (death recipient of P has not entered AMS
yet). And assume task T contains X, Y, Z. X and Y have
declared stateNotNeeded=true, so X and Y will be removed
from task T.

Now the size of task T changes from 3 to 1. And because
activityNdx=2 when updating Z, the next round (--activityNdx)
will have exception at activities.get(activityNdx):
IndexOutOfBoundsException: Invalid index 1, size is 1

The ActivityRecord in TaskRecord is removed by below flow:

ActivityStack.ensureActivitiesVisibleLocked
 ActivityStackSupervisor.startSpecificActivityLocked
  ActivityStackSupervisor.realStartActivityLocked
   ApplicationThreadProxy.scheduleLaunchActivity -> IPC fail
  ActivityManagerService.startProcessLocked
   ActivityManagerService.handleAppDiedLocked
    ActivityStackSupervisor.handleAppDiedLocked
     ActivityStack.handleAppDiedLocked
      ActivityStack.removeHistoryRecordsForAppLocked
       ActivityStack.removeActivityFromHistoryLocked
        task.removeActivity(r) -> mActivities.remove(r)

There is also similar patch to solve the same problem:
https://android-review.googlesource.com/143780/

Change-Id: Iac646bcb8ed3d3cfb2bda14e05e11abfcfe980d1

Former-commit-id: 3fe52da421abba355a51b8b5c6dd2ca073383c18