Revert "SELinuxMMAC unit tests"
Broken build.

frameworks/base/services/tests/servicestests/src/com/android/server/pm/SELinuxMMACTests.java:89: error: constructor PackageParser in class PackageParser cannot be applied to given types;
        PackageParser packageParser = new PackageParser(archiveFilePath);
                                      ^
  required: no arguments
  found: String
  reason: actual and formal argument lists differ in length
frameworks/base/services/tests/servicestests/src/com/android/server/pm/SELinuxMMACTests.java:93: error: method parsePackage in class PackageParser cannot be applied to given types;
        PackageParser.Package pkg = packageParser.parsePackage(sourceFile,
                                                 ^
  required: File,int
  found: File,String,DisplayMetrics,int
  reason: actual and formal argument lists differ in length
frameworks/base/services/tests/servicestests/src/com/android/server/pm/SELinuxMMACTests.java:99: error: incompatible types
        boolean savedCerts = packageParser.collectCertificates(pkg, 0);
                                                              ^
  required: boolean
  found:    void
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 errors
make: *** [out/target/common/obj/APPS/FrameworksServicesTests_intermediates/classes-full-debug.jar] Error 41

This reverts commit bbc1b9f5fe264211f29664ea3034149929481876 [formerly 2f446561f2f6d1b320b34432854d2f55e5b56f9e].

Change-Id: I0aa992d7b9eccce7e38c430a8a96084a6ee99866

Former-commit-id: 01a5aa95d9068f2babdc37ef7a98e280f1d0e6bc