Revert "AudioService: permission for volume adjustment to lowest values"
This reverts commit c99d355b5018b48aad03719fe73e2a15d5d72ffb [formerly a8f97ffdaadb510af5d7f67fbb75bd51cf4e909b].

Reason for revert: break git_master of errorprone target

out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/errorprone/srcjars/frameworks/base/services/core/java/com/android/server/audio/AudioService.java:4710: error: [EqualsNaN] == NaN always returns false; use the isNaN methods instead
                MIN_STREAM_VOLUME[AudioSystem.STREAM_ALARM], deviceForAlarm) == Float.NaN) {
                                                                             ^
    (see https://errorprone.info/bugpattern/EqualsNaN)
  Did you mean 'if (Float.isNaN(AudioSystem.getStreamVolumeDB(AudioSystem.STREAM_ALARM,'?

Bug: 157108450

Change-Id: Icf74dcbefccee6138473101e8dc23fba35faf5ce

Former-commit-id: 455d373861b3f77b0e403c8da48d5fc43ab17a20