DO NOT MERGE: Fixed NetworkStatsServiceTest and converted it to JUnit4.
Most tests were failing because due to a null NetworkCapabilities.
Example:

1) testNetworkStatsWifi(com.android.server.net.NetworkStatsServiceTest)
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.net.NetworkCapabilities.hasCapability(int)' on a null object reference
	at
	com.android.server.net.NetworkStatsService.updateIfacesLocked(NetworkStatsService.java:983)

BUG: 30839080

(cherry picked from commit 0e91eae9c3d0e8831e403a39e2f7ebc78f6bbafb [formerly 574f370c6da52eeffe747248d68ef044617c7bcf])

(cherry picked from commit 9c1cd49d0755704761cb49888c3ff696fd2a8174 [formerly 77cba4bdf6de8aec02efe0da7e84f17603912b21])

Change-Id: I6eee96178ade6adfc1406e06d5376206ca2420e5

Former-commit-id: fe46a2f8689f96e75c491d5c2477fe2caec2f289