Fix directory iteration when path disappears.
When iterating across `proc` directories, occasionally a directory would
disappear due to a process finishing. This often throws `IOException`
when accessing the directory, but can throw `DirectoryIteratorException`
if this happens during iteration:

  java.nio.file.DirectoryIteratorException: java.nio.file.NoSuchFileException: /proc/8708/task

This change catches `DirectoryIteratorException`.

Test: Build only (bug is difficult to reproduce).
Bug: 150888564

Change-Id: I7484d28231d0040b25dafc59b12b64a9342098a4

Former-commit-id: 52474456b79d54687bd27aa5d7ab397a0d1d83c1