Add conscrypt, okhttp, bouncycastle to the classpath when building stubs
When generating the stubs for android.test.mock, the main framework
source is also included. The source in turn has references to the
conscrypt, okhttp, and bouncycastle ibraries (e.g. ActivityThread.java uses
com.android.org.conscrypt.OpenSSLSocketImpl).

Although this does not break the build because doclava does not abort on
non-existing symbols, this creates a lot of error messages to the log
output:

frameworks/base/test-mock/../core/java/android/app/ActivityThread.java:143: error: package com.android.org.conscrypt does not exist
import com.android.org.conscrypt.OpenSSLSocketImpl;
                                ^
frameworks/base/test-mock/../core/java/android/app/ActivityThread.java:144: error: package com.android.org.conscrypt does not exist
import com.android.org.conscrypt.TrustedCertificateStore;
                                ^
...

Therefore adding the missing libraries to the classpath to prevent the
scary messages.

Test: mma -j under frameworks/base/test-mock does not show the error
messages.

Change-Id: I899be8ff7466f9483e4f3ae8328bc9c72bbe22ed

Former-commit-id: 97ca19f01382e411e3b1dc078364d37ae39b3758