Fix StatusBar setting disable flags before setting up
StatusBar#start() was was trying to initialize disable flags before
finishing start(). This triggered
NotificationEntryManager#setDisableNotificationAlerts() before calling
NEM setUpWithPresenter.

Fixed by moving the disable flag setup to a post-init task and making
sure we set up the notification state before doing anything crazy

Fixes: 118357487
Test: verifying that there are no systemui exceptions after rebooting
that look like this:
    java.lang.NullPointerException: Attempt to invoke virtual method
    'void android.database.ContentObserver.onChange(boolean)' on a null
    object reference

Change-Id: Id75a34c8f7414397d7f14de4b4638864262df426
(cherry picked from commit 114e80d78d42182f08322ad2ffc464b0cd89dadb [formerly b5d95d977cdb1454fe8fa717c1a89d0435c149e6])

Former-commit-id: a4bc7cd92b17682eb6c8e2604dc5a54cf949574a