Revert "Make CHANGE_APP_IDLE_STATE a system API"
This reverts commit 6d5385c6e4ba5d95a213548d02eedfcaaf3b7b1b [formerly c433ee54512c1aa472baad1930a40b319e7ce1a2].

Fails on walleye with:

java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions whitelist: {com.android.settings: android.permission.CHANGE_APP_IDLE_STATE, com.android.shell: android.permission.CHANGE_APP_IDLE_
STATE}

Bug: 63527785
Change-Id: I7a30615d20a6c22467a41d4b2d4f84f7702ce195

Former-commit-id: 8948c79fe0f5aaaaf52e7f418d871766fb2d8a76